[package]
name = "address"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
sha3 = "0.10.8"
ethnum = "1.5.0"
k256 = "0.13.2"
hex = "0.4"
arrayref = "0.3"